---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
        cloud: openstack
        region_name: regionOne
    register: r_os_servers
    tags: 
     - Delete_instance

  - name: Delete instances 
    os_server:
     cloud: openstack
     name: "{{ item.0 }}"
     state: absent 
#    debug: "{{ item.0 }} and {{ item.1 }}"
    with_together:
         - "{{ r_os_servers.openstack_servers | map(attribute='OS-EXT-SRV-ATTR:hostname')| list }}"
         - "{{ r_os_servers.openstack_servers | map(attribute='metadata.deployment_name')| list }}"
    when:  item.1  == 'QA' 
    tags: 
     - Delete_instance
